# Не просто создаём образ, но даём ему имя build
FROM gcc:12.5 AS build

RUN apt update && \
    apt install -y \
      python3-pip \
      python3-venv \
      cmake

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --no-cache-dir conan==1.*

COPY conanfile.txt /app/
RUN mkdir /app/build && cd /app/build && \
    conan install .. --build=missing -s compiler.libcxx=libstdc++11 -s build_type=Release

COPY ./src /app/src
COPY ./tests /app/tests
COPY CMakeLists.txt /app/

RUN cd /app/build && \
    cmake -DCMAKE_BUILD_TYPE=Release .. && \
    cmake --build . && ls

ENTRYPOINT ["/app/build/collision_detection_tests"]
